# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in cohesive_marketplace_middleware.gemspec
gemspec

gem "rake", "~> 13.0"

gem "rspec", "~> 3.0"

gem "standard", "~> 1.3"

gem "cohesive_marketplace_sdk", "~> 0.1.1"
